### ISSUE TITLE
Links to Feed and Entry documentation are broken

### ISSUE THREAD

**Issue by hainesr** [feedjira/feedjira-site#2]
On the Fetching and Parsing page (http://feedjira.com/fetching-and-parsing.html) the links to the Feed and Entry API documentation both point to http://link/to/docs?

**Comment by globalavocado** [comment]
All the links on the landing page that are enclosed by boxes are giving 404s: 

http://feedjira.com/upgrading.html
http://feedjira.com/fetching-and-parsing.html
http://feedjira.com/updating-feeds.html
http://feedjira.com/callbacks.html
http://feedjira.com/extending.html
http://feedjira.com/projects.html
http://feedjira.com/benchmarks.html

**Comment by jonallured** [comment]
Hi @globalavocado, I'm confused: the way you're describing the landing page sounds like you're getting the old version of the site. I just checked and I'm getting the right page. When I released version 2.0, I also re-wrote the landing page and those links enclosed in boxes are gone.

I guess you have a cached version of the page?

**Comment by globalavocado** [comment]
Is that possible if I got to the page via Google? I'm also getting this if I type feedjira.com into my browser.

**Comment by jonallured** [comment]
Well, I'm not sure what's going on, but I did ask a few other people to bring up the site and they are getting the correct version. I hate to ask, but have you tried different browsers or computers? Can't figure out why you're getting the old version of the site...

**Comment by globalavocado** [comment]
At work I go through a proxy, so that could explains that but I get the same at home with Chrome & Firefox (after clearing out the cache), maybe my ISP has also cached it. How long ago did you update the site?

**Comment by jonallured** [comment]
The new site went live about a week ago.

**Comment by hainesr** [comment]
It looks OK to me and I don't see all the links listed above by @globalavocado.

There is one broken link for me though: http://feedjira.com/stub in the Testing section.

**Comment by globalavocado** [comment]
Ok I wasn't aware it was updated so recently, it'll probably be ok for everybody very soon.

**Comment by jonallured** [comment]
@hainesr: good catch - I just fixed this and redeployed the site.
